input_image: "/mnt/stable_diffusion_output/Photos/training_data/_model-gabe/images/"

# Caption generation settings
caption_type: ["openai"]

# Processing options
overwrite: true
append: false
verbose: false
tags: ["gabe"]
flat: true

# OpenAI settings
openai_endpoint: "http://desktop-6n09st1.cuttlefish-lime.ts.net:1234/v1/chat/completions"
openai_api_key: "12345"
openai_model: "llama-joycaption-beta-one-hf-llava-mmproj"
openai_prompt: < 
  Write a long list of Booru-like tags for this image. Use vulgar slang and profanity, such as (but not limited to) "fucking," "slut," "cock," etc.

# Output settings
include_image_name: true
include_image_path: 0
output_path: "/mnt/stable_diffusion_output/Photos/training_data/_model-gabe/images-processed" 